# Generated by Django 4.1.2 on 2022-10-30 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_numericquestion_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numericquestion',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.category'),
        ),
        migrations.AlterField(
            model_name='pickquestion',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.category'),
        ),
    ]
