# Generated by Django 4.1.5 on 2023-02-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_delete_testimagemodel_remove_imagequestion_image_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-popularity',)},
        ),
        migrations.AlterField(
            model_name='imagequestion',
            name='image',
            field=models.ImageField(upload_to='image_question/'),
        ),
        migrations.AlterField(
            model_name='imagequestion',
            name='question',
            field=models.CharField(default='Co je na obrázku?', max_length=255),
        ),
    ]
